version: '3'
services:
  solr:
    image: solr:8
    ports:
      - "8983:8983"
    volumes:
      - ./solr/data:/var/solr/data
    command:
      - solr-precreate
      - phrases
    networks:
      - esnet

networks: 
  esnet: